export CTX_EASYINSTALL_HOSTNAME=$(hostname)
export CTX_EASYINSTALL_DNS=10.110.193.31
export CTX_EASYINSTALL_NTPS=10.110.193.31
export CTX_EASYINSTALL_DOMAIN="BOBYXEN"
export CTX_EASYINSTALL_REALM="BOBYXEN.COM"
export CTX_EASYINSTALL_FQDN="bobyxenad1.bobyxen.com"
export CTX_EASYINSTALL_ADINTEGRATIONWAY=winbind
export CTX_EASYINSTALL_USERNAME=Administrator
export CTX_EASYINSTALL_PASSWORD=Citrix123
export CTX_XDL_SUPPORT_DDC_AS_CNAME=N
export CTX_XDL_DDC_LIST=bddcvmw1.bobyxen.com
export CTX_XDL_VDA_PORT=80
export CTX_XDL_REGISTER_SERVICE=Y
export CTX_XDL_ADD_FIREWALL_RULES=Y
export CTX_XDL_HDX_3D_PRO=N
export CTX_XDL_VDI_MODE=N
export CTX_XDL_SITE_NAME=none
export CTX_XDL_LDAP_LIST=bobyxenad1.bobyxen.com:389
export CTX_XDL_SEARCH_BASE="DC=bobyxen,DC=com"
export CTX_XDL_FAS_LIST=none
export CTX_XDL_DOTNET_RUNTIME_PATH=/opt/dotnet
export CTX_XDL_DESKTOP_ENVIRONMENT=gnome
export CTX_XDL_TELEMETRY_SOCKET_PORT=7503
export CTX_XDL_TELEMETRY_PORT=750 
export CTX_XDL_START_SERVICE=Y

sudo -E /opt/Citrix/VDA/sbin/ctxinstall.sh

